Select 
ACTIVITY_DT as "DATE",
SLS_DIST_CHNL_TYPE_DESC,
PREPAID_IND,
SEGMENT,
SUBSEGMENT,
VZ2_AREA_CD,
GROSS_ADDS_TOTAL
from COE_UAT_ALLVM.TSPOT_VZW_FACT_ONE_EX_SUMMARY_V
--from COE_UAT_ALLVM.UAT_TSPOT_VZW_FACT_ONE_EX_SUMMARY_V
WHERE (ACTIVITY_DT BETWEEN ADD_MONTHS(TD_MONTH_BEGIN(CURRENT_DATE-2),-36) AND CURRENT_DATE-1
);